
---

- name: Ajout de dépendances pour les versions de PHP.
  become: true
  apt:
    name:
      - apt-transport-https
      - ca-certificates
    state: present

- name: Ajouter la clé apt d'Ondrej Sury.
  become: true
  apt_key:
    url: https://packages.sury.org/php/apt.gpg
    id: 15058500A0235D97F5D10063B188E2B695BD4743
    state: present

- name: Ajouter le dépôt Ondrej Sury.
  become: true
  apt_repository:
    repo: "deb https://packages.sury.org/php/ {{ ansible_distribution_release }} main"
    state: present

- name : Installation de PHP pour Laravel
  become: true
  apt:
    name :
      - php8.0-fpm
      - php8.0-mysql
      - php8.0-mbstring
      - php8.0-xml
      - php8.0-zip
      - libapache2-mod-php
      - zip
      - unzip
      - php-xml
      - php-curl
    state : present

- name: Télécharger Composer
  become : yes
  tags: composer
  get_url:
    url: https://getcomposer.org/installer
    dest: /tmp/composer-setup.php

- name: Installer Composer
  become : yes
  tags: composer
  command: php /tmp/composer-setup.php --install-dir=/usr/bin --filename=composer

- name: Mise à jour de la dernière version de composer
  become : yes
  tags: composer
  command: composer selfupdate

- name : Cloner le dépôt Laravel API
  become: true
  git :
    repo: https://github.com/Nico-Dobrowolski/api.git
    dest: /var/www/api

- name: Télécharger et mettre à jour toutes les bibliothèques et dépendances
  become : yes
  composer:
    command : update
    working_dir: /var/www/api
  environment:
    COMPOSER_NO_INTERACTION: "1"

- name: Désactiver le site Apache par défaut
  become : yes
  shell: /usr/sbin/a2dissite 000-default.conf

- name: Activer mod_rewrite
  become : yes
  apache2_module: name=rewrite state=present

- name: Activer mod_headers
  become : yes
  apache2_module: name=headers state=present
## Handel
- name: Redémarré Apache2 
  become : yes
  service: name=apache2 state=restarted

- name : Configuration d'un hôte virtuel pour le Laravel API
  become : yes
  template :
    src : api.com.conf
    dest : /etc/apache2/sites-available/

- name: Activer le site Laravel API
  become : yes
  shell: /usr/sbin/a2ensite api.com.conf

- name: Redémarré Apache2
  become : yes
  service: name=apache2 state=restarted

- name: Modifier les autorisations [Fichier]
  become : yes
  shell : find /var/www/api -type f -exec chmod 777 {} -R \;

- name: Modifier les autorisations [Dossier]
  become : yes
  shell : find /var/www/api -type d -exec chmod 777 {} -R \;