---
- name: Ajouter la clé nodejs apt
  become: true
  apt_key:
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
    state: present

- name: Ajouter le dépôt nodejs 16.x
  become: true
  apt_repository:
    repo: deb https://deb.nodesource.com/node_16.x {{ ansible_distribution_release }} main
    update_cache: yes

- name: Installer nodejs
  become: true
  apt:
    update_cache: yes
    name: nodejs
    state: latest

- name : cloner le dépôt react app
  become: true
  git :
    repo: https://github.com/Nico-Dobrowolski/app.git
    dest: /opt/app

- name : Copier le fichier .env.production dans /opt/app
  become : yes
  copy:
    src : .env.production
    dest : /opt/app

- name: Initialisation de l'application
  become: true
  command: npm i
  args:
    chdir: "/opt/app"

- name: Construire l'application en mode production
  become: true
  command: npm run build
  args:
    chdir: "/opt/app"

- name: Copier l'application dans var/www
  become: true
  copy:
    remote_src : yes
    src: /opt/app/build
    dest: /var/www

- name : Copier .htaccess dans /var/www/build
  become : yes
  copy:
    src : .htaccess
    dest : /var/www/build

- name : Configurer un hôte virtuel pour l'application React
  become : yes
  template :
    src : app.com.conf
    dest : /etc/apache2/sites-available/

- name: Activer le site de l'application React
  become : yes
  shell: /usr/sbin/a2ensite app.com.conf

- name: Désactiver le site Apache par défaut
  become : yes
  shell: /usr/sbin/a2dissite 000-default.conf

- name: Activer mod_rewrite
  become : yes
  apache2_module: name=rewrite state=present

- name: Redémarré Apache2
  become : yes
  service: name=apache2 state=restarted
