---

- name: Exécuter [apt-get update]
  become: true
  apt:
    update_cache: yes

- name : Installation des outils par défaut
  become: true
  apt:
    name :
      - apache2
      - git
      - curl
      - wget
      - npm
    state : present