---

- name: Run the equivalent of "apt-get update" as a separate step
  become: true
  apt:
    update_cache: yes

- name : Installation des tools
  become: true
  apt: name={{ item }} state=latest
  with_items:
    - apache2
    - git
    - curl
    - wget
    - npm