---

- name: Run apt of "apt-get update" as a separate step
  become: true
  apt:
    update_cache: yes

- name : Installation de PHP for Laravel with Apache
  become: true
  apt:
    name :
      - apache2
      - git
      - curl
      - wget
      - npm
    state : present