---
- name : Installation de fail2ban
  become : yes
  apt: name=fail2ban state=latest

- name : Configuration fail2ban
  become : yes
  copy:
    src : defaults-debian.conf
    dest : /etc/fail2ban/jail.d/defaults-debian.conf
    owner : root
    group : root
    mode : 0644

- name : Start fail2ban
  become : yes
  service : name=fail2ban state=started enabled=true

- name : Restart fail2ban
  become : yes
  service : name=fail2ban state=restarted enabled=true

