---
- name : Installation des serveur web
  hosts : machine.1
  remote_user: vagrant
  roles:
    - utils
    - motd
    - apache
    - react-deploy

- name : Installation de l'API
  hosts : machine.2
  remote_user: vagrant
  roles:
    - utils
    - motd
    - apache
    - laravel-deploy
...